### ISSUE TITLE
Great works!  while i use String as 'workflow:input',  when i use it,  the main workflow node can't convert widget to input

### ISSUE THREAD

**Issue by leeooo001** [numz/Comfyui-FlowChain#1]
Great works! 
while i use String as 'workflow:input',  when i use it,  the main workflow node can't convert widget to input

**Comment by numz** [comment]
Hi,

I was waiting for this one :D
You need to update comfyui, I found this bug in comfyui too, so I ask them and they fix it. 
[pull request of this bug in comfyui](https://github.com/Comfy-Org/ComfyUI_frontend/issues/1114)

so just update comfyui, must works.
the **comfyui frontend** version must be at least : 1.3.11

unfortunetly, 1.3.11 add new bugs... so I've update the repository, so update the package in comfyui, but you'll see strange outputs with "*", for fix you have to recreate the node.

Sorry about that.

let me know :)
