### ISSUE TITLE
I can't place a Workflow node

### ISSUE THREAD

**Issue by hughescr** [numz/Comfyui-FlowChain#4]
**Describe the bug**
I can't place a FlowChain workflow node in my workflow, either through the node search menu, nor through the "Add node" submenu.

**To Reproduce**
1. Create a new fresh empty workflow
2. double-click to open node search, find flowchain workflow node, select it
3. ...
4. nothing happens. No node placed, no error message, the node search menu collapses.

**Expected behavior**
A workflow node should be placed in my new workflow, and allow me to select workflows I saved in the api folder.

**Desktop (please complete the following information):**
 - OS: Mac OS 15.0.2
 - Browser Safari
 - Python 3.12.7

**Comment by hughescr** [comment]
if you have a sample workflow JSON using the flowchain workflow node, share it and I'll load it and see if the node fails to load that way...

**Comment by hughescr** [comment]
Ah actually, I thought to look in the browser console, and found this:

```
[Error] TypeError: undefined is not an object (evaluating 'Object.keys(app.lipsync_studio)')
keys
(anonymous function) — jsnodes.js:627
createNode — litegraph.es.js:2818
(anonymous function) — use_everywhere.js:280
addNodeOnGraph — app.ts:2968
(anonymous function) — NodeSearchBoxPopover.vue:81
callWithErrorHandling — runtime-core.esm-bundler.js:195
callWithAsyncErrorHandling — runtime-core.esm-bundler.js:202
emit — runtime-core.esm-bundler.js:726
callWithErrorHandling — runtime-core.esm-bundler.js:195
callWithAsyncErrorHandling — runtime-core.esm-bundler.js:202
emit — runtime-core.esm-bundler.js:726
onOptionSelect — index.mjs:521
callWithErrorHandling — runtime-core.esm-bundler.js:195
callWithAsyncErrorHandling — runtime-core.esm-bundler.js:202
(anonymous function) — runtime-dom.esm-bundler.js:693

	logError (index-DGAbdBYF.js:3325)
	handleError (index-DGAbdBYF.js:3306)
	callWithErrorHandling (index-DGAbdBYF.js:3249)
	callWithAsyncErrorHandling (index-DGAbdBYF.js:3255)
	emit (index-DGAbdBYF.js:3810)
	callWithErrorHandling (index-DGAbdBYF.js:3247)
	callWithAsyncErrorHandling (index-DGAbdBYF.js:3255)
	emit (index-DGAbdBYF.js:3810)
	onOptionSelect (GraphView-CVV2XJjS.js:1621)
	callWithErrorHandling (index-DGAbdBYF.js:3247)
	callWithAsyncErrorHandling (index-DGAbdBYF.js:3255)
	(anonymous function) (index-DGAbdBYF.js:12087)
```

**Comment by hughescr** [comment]
I did this and I can place the workflow node.  idk why the JS is trying to access that lipsync thing which doesn't exist, or if there's a side-effect of removing it...

```
diff --git i/web/js/jsnodes.js w/web/js/jsnodes.js
index 465a4c3..6b4744a 100644
--- i/web/js/jsnodes.js
+++ w/web/js/jsnodes.js
@@ -624,9 +624,9 @@ app.registerExtension({
                             importWorkflow(this, value, app)
                         }
                     },{
-                        values: ["None", ...Object.keys(app.lipsync_studio)]
+                        values: ["None", ]
                     });
-                    if(!workflow_reload || !filename in app.lipsync_studio){
+                    if(!workflow_reload){
                         cleanInputs(this);
                     }
                     this.color = "#004670";
```

**Comment by numz** [comment]
Hi sorry about that,

Yes, I made a recent change. If you haven't done so, please update FlowChain. Don't worry about the variable name "lipsync_studio" — it's not very intuitive, but it actually contains the list of workflows. There's no need to be concerned about it.

Could you let me know if it's working now?

**Comment by hughescr** [comment]
Seems to be working now on HEAD

**Comment by kaldigo** [comment]
I am having this same issue at the moment.

Edit: I figured it out. For anyone else having this issue, it turned out I didn't have websocket-client installed.
