### ISSUE TITLE
Workflow produces error when trying to execute the graph

### ISSUE THREAD

**Issue by vfxGuy845** [numz/Comfyui-FlowChain#5]
I've created a workflow and it loads properly, but when I try to execute the graph I get this error. What could the cause of this be? I wouldn't think permissions would be an issue with these nodes.

<img width="1155" alt="image" src="https://github.com/user-attachments/assets/ddc03fd7-dd78-453e-8518-a84b95121a70">

**Comment by numz** [comment]
Hi,
Can you share the Resize_to_Max.json, the cmd output, and the "show_report" please?

**Comment by cardenluo** [comment]
![image](https://github.com/user-attachments/assets/e34ff34f-bc31-4e3f-af29-6e4a270b85b0)
I get the same bug.
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-10-19 23:12:44.859725
** Platform: Windows
** Python version: 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]
** Python executable: F:\ComfyUI_windows_portable\python_embeded\python.exe
** ComfyUI Path: F:\ComfyUI_windows_portable\ComfyUI
** Log path: F:\ComfyUI_windows_portable\ComfyUI\comfyui.log

Prestartup times for custom nodes:
   0.0 seconds: F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Easy-Use
   0.0 seconds: F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy
  18.6 seconds: F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 24576 MB, total RAM 65384 MB
pytorch version: 2.4.1+cu124
xformers version: 0.0.28.post1
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3090 : cudaMallocAsync
Using xformers cross attention

**Comment by numz** [comment]
Hi, @cardenluo @vfxGuy845 
I have update the "Workflow Input" Node, can you update the custom node from manager and let me know please?

**Comment by cardenluo** [comment]
![image](https://github.com/user-attachments/assets/9866d37e-1659-43de-a38e-d769ea74c6e2)
![image](https://github.com/user-attachments/assets/53fed1ea-a0cd-4dfe-9bb1-3b8109ee0465)
node is ok ,but output is nothing .

**Comment by numz** [comment]
@cardenluo 
Can you send me cmd output, and your workflow please?

also, try to give unique name to inputs I see 2 "img_orc"
let me know

**Comment by cardenluo** [comment]
got prompt
[]
[Prompt Server] web root: F:\ComfyUI_windows_portable\ComfyUI\web
workflow : 1.json
node : 5013 WorkflowInput image_count => 1
node : 5015 WorkflowInput {'Name': 'image_scale', 'type': 'INT', 'default': 512}
node : 5006 easy imageScaleDownToSize {'size': ['5015', 0], 'mode': False, 'images': ['5013', 0]}
node : 5011 easy imageRemBg {'rem_mode': 'Inspyrenet', 'image_output': 'Preview', 'save_prefix': 'ComfyUI', 'torchscript_jit': False, 'images': ['5006', 0]}
Settings -> Mode=base, Device=cuda:0, Torchscript=disabled
Inspyrenet Rembg: 100%|██████████| 1/1 [00:00<00:00,  1.04it/s]
!!! Exception during processing !!! Object of type Tensor is not JSON serializable
Traceback (most recent call last):
  File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-FlowChain\workflow.py", line 301, in executes
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all,
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-FlowChain\workflow.py", line 108, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True,
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-FlowChain\workflow.py", line 84, in _map_node_over_list
    process_inputs(input_dict, i)
  File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-FlowChain\workflow.py", line 73, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Easy-Use\py\image.py", line 789, in remove
    results = easySave(new_images, save_prefix, image_output, prompt, extra_pnginfo)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Easy-Use\py\libs\utils.py", line 253, in easySave
    results = PreviewImage().save_images(images, filename_prefix, prompt, extra_pnginfo)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1511, in save_images
    metadata.add_text("prompt", json.dumps(prompt))
                                ^^^^^^^^^^^^^^^^^^
  File "json\__init__.py", line 231, in dumps
  File "json\encoder.py", line 200, in encode
  File "json\encoder.py", line 258, in iterencode
  File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-0246\nodes.py", line 1113, in wrapper_encoder_func_handle
    return DEFAULT_JSON_ENCODER(self, obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1.json](https://github.com/user-attachments/files/17448985/1.json)

  File "json\encoder.py", line 180, in default
TypeError: Object of type Tensor is not JSON serializable

**Comment by cardenluo** [comment]
[API-CN22.json](https://github.com/user-attachments/files/17448989/API-CN22.json)
![image](https://github.com/user-attachments/assets/1aabe377-b7c2-483c-ae1b-6a5e37afd0f8)

**Comment by cardenluo** [comment]
I think this might be my issue; I used Chinese naming, which caused the error? Using full English, this would be normal. 
![image](https://github.com/user-attachments/assets/2e91960c-2d50-42f9-9863-4723c99fd84d)

**Comment by numz** [comment]
ok, thanks for feedback, I don't figure that, I'll try to take care about this in next updates

**Comment by vfxGuy845** [comment]
Here is the json you requested. My error happens to all Workflow's I create when I try to execute them.

[Resize_To_Max.json](https://github.com/user-attachments/files/17468264/Resize_To_Max.json)

**Comment by numz** [comment]
@vfxGuy845 
I have tried to  reproduce your workflow:
![image](https://github.com/user-attachments/assets/4c9035ce-e523-4141-ab08-d0f9d5b27202)


for others workflows I don't know but for this one I found it miss the "image" that goes to the "ImageResize+" "image" input.
can you check please?

**Comment by vfxGuy845** [comment]
It's weird, everything is connected when I save the json. But when I load that json back into comfy the workflow nodes are disconnected from the rest of the graph.

<img width="1505" alt="disconnected" src="https://github.com/user-attachments/assets/1a943b1d-b3c0-46f6-bb0f-3d262d4a8a1b">

**Comment by vfxGuy845** [comment]
Here is an updated json that loads with everything connected. I still get the same error.
[Resize_To_Max.json](https://github.com/user-attachments/files/17468714/Resize_To_Max.json)

**Comment by numz** [comment]
Ok thanks for feed back,
can you tell me your comfyui-frontend version please?
settings and at the top you must see the version.

**Comment by vfxGuy845** [comment]
For sure, here's the Comfy info. I'm not sure if it matters but I'm running Comfy through Stability Matrix.
<img width="412" alt="image" src="https://github.com/user-attachments/assets/282d6f20-9aed-415f-9cce-b7d1a367431b">

**Comment by IMParesqui** [comment]
So, what was the conclusion of this topic? I'm getting the same error...
