### ISSUE TITLE
Realizing it doesn't need to run again... 

### ISSUE THREAD

**Issue by cchance27** [numz/Comfyui-FlowChain#7]
**Is your feature request related to a problem? Please describe.**
Rerunning the main workflow seems to always rerun the sub-workflow, would be nice if the Workflow Node could know if no inputs have changed, and if the underlying workflow doesn't have any auto changing things to just return the same output.

**Describe the solution you'd like**
If no changes to inputs, return the old outputs that were already computed, that way we don't have to rerun the sub workflows every time the main workflow runs.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by numz** [comment]
Hi 
I see what you mean, this depend of the sub workflow content, sometimes nodes allways rerun...
A good way to check this is to load the subworkflow and run it twice to see if some notes are rerun each time.

Perhaps you can send me a subworkflow(original one, not the api one) that have this issue.
Ill try to check why.

**Comment by cchance27** [comment]
I think i found the issue it feels like this is already working, i think i had a bug in the subflow which was actually causing it to need to rerun so gonna close this
